name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install and Build
              run: |
                  npm install
                  npm run-script test
                  npm run-script build
                  npm run-script test

            - name: Build and publish Docker image
              if: github.ref == 'refs/heads/master'
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: farao/gridcapa-app
                  username: farao
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
